"""KVI (Key Value Indicators) calculation router."""

import uuid
from datetime import date
from decimal import Decimal
from fastapi import APIRouter
from sqlalchemy import select, func
from sqlalchemy.orm import selectinload
from pydantic import BaseModel

from app.dependencies import DbSession, CurrentSessionOrgId
from app.models import Project, Task, Initiative, InitiativeTaskLink, InitiativeTaskValue

router = APIRouter(prefix="/kvi", tags=["KVI"])


class PortfolioHealthSummary(BaseModel):
    """Portfolio health summary KPI."""
    total_projects: int
    active_projects: int
    on_track: int
    at_risk: int
    late: int
    completed: int
    schedule_variance_days: float
    cost_variance_percent: float
    resource_utilization_percent: float


class InitiativeValueSummary(BaseModel):
    """Summary of value generated by initiatives."""
    total_value: dict[str, Decimal]
    by_initiative: list[dict]


@router.get("/portfolio-health", response_model=PortfolioHealthSummary)
async def get_portfolio_health(db: DbSession, org_id: CurrentSessionOrgId):
    """Calculate portfolio health summary across all projects."""
    # Get all projects
    result = await db.execute(
        select(Project)
        .where(Project.org_id == org_id)
        .options(selectinload(Project.tasks))
    )
    projects = list(result.scalars().all())
    
    total_projects = len(projects)
    active_projects = sum(1 for p in projects if p.status == "Active")
    on_track = sum(1 for p in projects if p.health == "On Track")
    at_risk = sum(1 for p in projects if p.health == "At Risk")
    late = sum(1 for p in projects if p.health == "Late")
    completed = sum(1 for p in projects if p.status == "Completed")
    
    # Calculate schedule variance
    today = date.today()
    total_variance_days = 0
    projects_with_dates = 0
    
    for project in projects:
        if project.end_date and project.original_end_date:
            variance = (project.end_date - project.original_end_date).days
            total_variance_days += variance
            projects_with_dates += 1
    
    avg_schedule_variance = total_variance_days / projects_with_dates if projects_with_dates > 0 else 0
    
    # Calculate cost variance (estimate vs actual hours)
    total_estimate = 0
    total_actual = 0
    
    for project in projects:
        for task in project.tasks:
            total_estimate += task.estimate or 0
            total_actual += task.actual or 0
    
    cost_variance = ((total_actual - total_estimate) / total_estimate * 100) if total_estimate > 0 else 0
    
    # Resource utilization would require more complex calculation
    # Simplified: based on assigned vs available
    resource_utilization = 75.0  # Placeholder
    
    return PortfolioHealthSummary(
        total_projects=total_projects,
        active_projects=active_projects,
        on_track=on_track,
        at_risk=at_risk,
        late=late,
        completed=completed,
        schedule_variance_days=avg_schedule_variance,
        cost_variance_percent=cost_variance,
        resource_utilization_percent=resource_utilization
    )


@router.get("/initiative-value", response_model=InitiativeValueSummary)
async def get_initiative_value(db: DbSession, org_id: CurrentSessionOrgId):
    """Calculate total value generated by initiatives."""
    # Get all initiatives with task links and values
    result = await db.execute(
        select(Initiative)
        .where(Initiative.org_id == org_id)
        .options(
            selectinload(Initiative.task_links).selectinload(InitiativeTaskLink.values)
        )
    )
    initiatives = list(result.scalars().all())
    
    total_value: dict[str, Decimal] = {}
    by_initiative = []
    
    for initiative in initiatives:
        init_values: dict[str, Decimal] = {}
        
        for link in initiative.task_links:
            for value in link.values:
                metric = value.metric_name
                amount = value.value or Decimal(0)
                
                # Add to initiative totals
                init_values[metric] = init_values.get(metric, Decimal(0)) + amount
                
                # Add to grand totals
                total_value[metric] = total_value.get(metric, Decimal(0)) + amount
        
        by_initiative.append({
            "id": str(initiative.id),
            "name": initiative.name,
            "status": initiative.status,
            "values": {k: float(v) for k, v in init_values.items()}
        })
    
    return InitiativeValueSummary(
        total_value=total_value,
        by_initiative=by_initiative
    )


@router.get("/schedule-variance")
async def get_schedule_variance(db: DbSession, org_id: CurrentSessionOrgId):
    """Get detailed schedule variance by project."""
    result = await db.execute(
        select(Project).where(Project.org_id == org_id)
    )
    projects = list(result.scalars().all())
    
    variances = []
    for project in projects:
        if project.end_date and project.original_end_date:
            variance_days = (project.end_date - project.original_end_date).days
            variances.append({
                "project_id": str(project.id),
                "project_name": project.name,
                "original_end_date": project.original_end_date.isoformat() if project.original_end_date else None,
                "current_end_date": project.end_date.isoformat() if project.end_date else None,
                "variance_days": variance_days,
                "status": "behind" if variance_days > 0 else "ahead" if variance_days < 0 else "on_schedule"
            })
    
    return {
        "projects": variances,
        "summary": {
            "behind_schedule": sum(1 for v in variances if v["variance_days"] > 0),
            "on_schedule": sum(1 for v in variances if v["variance_days"] == 0),
            "ahead_schedule": sum(1 for v in variances if v["variance_days"] < 0)
        }
    }
